In [1]:
import numpy as np
import time

In [2]:
# scalar shape is ()
# column vector shape is (m,)
# matrix shape is (m,n)

# 1D array of zeros (column vector of zeros):
a = np.zeros(5)
print(a)
print(a.shape)
print(a.dtype)

[0. 0. 0. 0. 0.]
(5,)
float64


In [3]:
# 1D array of random numbers (column vector of random numbers):
b = np.random.random_sample(5)
print(b)
print(b.shape)
print(b.dtype)

[0.60972684 0.30312825 0.34871023 0.49674951 0.80214617]
(5,)
float64


In [4]:
# 1D array of equally spaced numbers (column vector):
c = np.arange(5)
print(c)
print(c.shape)
print(c.dtype)

[0 1 2 3 4]
(5,)
int64


In [5]:
# 1D array of user-specified numbers (column vector):
d = np.array([2,5,6,8,9])
print(d)
print(d.shape)
print(d.dtype,"\n")

print(d[0])
print(d[0].shape)
print(d[0].dtype,"\n")

# slicing [start:stop:step]:
print(d[1:3:1])
print(d[1:3:1].shape)
print(d[1:3:1].dtype,"\n")

print(d[:3]) # same as d[0:3]
print(d[3:])
print(d[:])

[2 5 6 8 9]
(5,)
int64 

2
()
int64 

[5 6]
(2,)
int64 

[2 5 6]
[8 9]
[2 5 6 8 9]


In [6]:
# List of numbers (coma in between):
f = [2,5,7,8]
print(f)

[2, 5, 7, 8]


In [7]:
# 2D array of zeros (matrix of zeros):
# argument of the zeros function is a tuple (m,n)
a2 = np.zeros((2,4))
print(a2)
print(a2.shape)
print(a2.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(2, 4)
float64


In [8]:
# 2D array of random numbers (matrix of random numbers):
b2 = np.random.random_sample((2,4))
print(b2)
print(b2.shape)
print(b2.dtype)

[[0.47968598 0.46058416 0.34738965 0.52029414]
 [0.94137932 0.12805073 0.13569887 0.45744217]]
(2, 4)
float64


In [9]:
# 2D array of user-specified numbers (matrix):
d2 = np.array([[2,5,6,8],[1,2,3,4]])
print(d2)
print(d2.shape)
print(d2.dtype)

[[2 5 6 8]
 [1 2 3 4]]
(2, 4)
int64


In [10]:
# dot product by defining a for-loop:
def dot_prod(a,b):
    c = 0
    for i in range(len(a)):
        c = c + a[i]*b[i]
    
    return c

In [11]:
dot_prod(d,c)

77

In [12]:
# dot product using vectorization and pre-existing function:
np.dot(d,c)

77